name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CHART_NAME: ghcr.io/tomkerkhove/ghcr-example-chart

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Helm tool installer
        uses: Azure/setup-helm@v1

      - name: Enable experimental Helm features
        run: export HELM_EXPERIMENTAL_OCI=1

      - name: Locally save new Helm chart locally
        run: helm chart save .\charts\${{ env.CHART_NAME }}\ ghcr.io/tomkerkhove/${{ env.CHART_NAME }}

      - name: Login to GitHub Container Registry
        run: helm registry login --username tomkerkhove --password ${{ secrets.GITHUB_TOKEN }}  ghcr.io/tomkerkhove

      - name: Push Helm chart to GitHub Container Registry
        run: helm chart push ghcr.io/tomkerkhove/${{ env.CHART_NAME }}:0.1.0
